"""
AI Home Gym — Curated Exercise Database Seeder
Replaces the Wger mass-import with a carefully curated set of ~85 exercises
across 11 categories. Each exercise has proper metadata for AI training,
recommendations, and form detection.

Run from project root:
  python scripts/seed_exercises.py
"""

import pymongo
import sys
from datetime import datetime

MONGO_URI = "mongodb://localhost:27017/ai_home_gym"

# ─── Curated Exercise Database ────────────────────────────────────────────────
# Fields:
#   name, description, primary_category, categories (list),
#   difficulty, equipment (list), muscles_primary (list),
#   muscles_secondary (list), calories_per_min, reps_default,
#   sets_default, duration_seconds (for timed exercises),
#   ai_supported (LSTM form detection ready), instructions (list of steps),
#   common_mistakes (list), reference_gif (empty — added later)

EXERCISES = [

    # ── 🧘 YOGA ───────────────────────────────────────────────────────────────
    {
        "name":             "Mountain Pose",
        "description":      "A foundational standing yoga pose that improves posture, balance, and body awareness. The starting point for most standing poses.",
        "primary_category": "Yoga",
        "categories":       ["Yoga", "Flexibility & Mobility", "Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps", "Abs"],
        "muscles_secondary":["Calves", "Glutes"],
        "calories_per_min": 2,
        "reps_default":     None,
        "sets_default":     1,
        "duration_seconds": 30,
        "ai_supported":     True,
        "instructions": [
            "Stand with feet together, arms at sides",
            "Distribute weight evenly across both feet",
            "Engage thighs, lift kneecaps slightly",
            "Lengthen tailbone toward the floor",
            "Inhale, lengthen spine upward",
            "Hold for 5-10 breaths"
        ],
        "common_mistakes":  ["Locking knees", "Holding breath", "Slouching shoulders"],
        "reference_gif":    "",
    },
    {
        "name":             "Downward Dog",
        "description":      "An iconic yoga pose that stretches the hamstrings, calves, and spine while strengthening the arms and shoulders.",
        "primary_category": "Yoga",
        "categories":       ["Yoga", "Flexibility & Mobility"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Hamstrings", "Calves"],
        "muscles_secondary":["Shoulders", "Triceps", "Lats"],
        "calories_per_min": 3,
        "reps_default":     None,
        "sets_default":     3,
        "duration_seconds": 30,
        "ai_supported":     True,
        "instructions": [
            "Start on hands and knees",
            "Tuck toes under and lift hips up and back",
            "Straighten legs as much as comfortable",
            "Press hands firmly into the floor",
            "Keep head between arms, ears level with upper arms",
            "Hold for 5-10 breaths"
        ],
        "common_mistakes":  ["Rounding the back", "Bending knees excessively", "Collapsing chest"],
        "reference_gif":    "",
    },
    {
        "name":             "Cobra Pose",
        "description":      "A gentle backbend that strengthens the spine and opens the chest. Excellent for counteracting desk posture.",
        "primary_category": "Yoga",
        "categories":       ["Yoga", "Flexibility & Mobility", "Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Spinal Erectors", "Chest"],
        "muscles_secondary":["Shoulders", "Abs"],
        "calories_per_min": 2,
        "reps_default":     None,
        "sets_default":     3,
        "duration_seconds": 20,
        "ai_supported":     False,
        "instructions": [
            "Lie face down with hands under shoulders",
            "Press tops of feet into floor",
            "Inhale and slowly lift chest off floor",
            "Keep elbows slightly bent",
            "Roll shoulders back and down",
            "Hold for 15-20 seconds"
        ],
        "common_mistakes":  ["Overextending neck", "Pushing too high", "Lifting hips"],
        "reference_gif":    "",
    },
    {
        "name":             "Child's Pose",
        "description":      "A resting yoga pose that gently stretches the hips, thighs, and lower back. Used as a rest between more intense poses.",
        "primary_category": "Yoga",
        "categories":       ["Yoga", "Flexibility & Mobility", "Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Hip Flexors", "Lower Back"],
        "muscles_secondary":["Glutes", "Ankles"],
        "calories_per_min": 1,
        "reps_default":     None,
        "sets_default":     1,
        "duration_seconds": 60,
        "ai_supported":     False,
        "instructions": [
            "Kneel on floor with toes together",
            "Sit back on heels",
            "Separate knees hip-width apart",
            "Exhale and fold torso between thighs",
            "Extend arms forward or rest alongside body",
            "Hold for 1-3 minutes"
        ],
        "common_mistakes":  ["Tensing shoulders", "Lifting hips off heels"],
        "reference_gif":    "",
    },
    {
        "name":             "Warrior I",
        "description":      "A powerful standing pose that strengthens the legs, opens the hips and chest, and builds focus and stability.",
        "primary_category": "Yoga",
        "categories":       ["Yoga", "Lower Body"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps", "Hip Flexors"],
        "muscles_secondary":["Glutes", "Calves", "Shoulders"],
        "calories_per_min": 4,
        "reps_default":     None,
        "sets_default":     2,
        "duration_seconds": 30,
        "ai_supported":     False,
        "instructions": [
            "Stand and step one foot back 3-4 feet",
            "Turn back foot out 45 degrees",
            "Bend front knee over front ankle",
            "Square hips toward front",
            "Raise arms overhead, palms facing",
            "Hold for 5 breaths each side"
        ],
        "common_mistakes":  ["Front knee caving in", "Back heel lifting", "Hunching shoulders"],
        "reference_gif":    "",
    },
    {
        "name":             "Warrior II",
        "description":      "A standing yoga pose that builds strength in the legs and core while improving stamina, concentration, and balance.",
        "primary_category": "Yoga",
        "categories":       ["Yoga", "Lower Body"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps", "Glutes"],
        "muscles_secondary":["Inner Thighs", "Shoulders", "Abs"],
        "calories_per_min": 4,
        "reps_default":     None,
        "sets_default":     2,
        "duration_seconds": 30,
        "ai_supported":     False,
        "instructions": [
            "Step feet wide apart (about 4 feet)",
            "Turn right foot out 90 degrees, left foot in slightly",
            "Bend right knee over right ankle",
            "Extend arms parallel to floor",
            "Gaze over right fingertips",
            "Hold for 5 breaths each side"
        ],
        "common_mistakes":  ["Knee extending past ankle", "Collapsing front hip", "Dropping arms"],
        "reference_gif":    "",
    },
    {
        "name":             "Tree Pose",
        "description":      "A balancing yoga pose that strengthens the legs and core while improving focus and concentration.",
        "primary_category": "Yoga",
        "categories":       ["Yoga", "Rehabilitation"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps", "Abs"],
        "muscles_secondary":["Inner Thighs", "Glutes", "Calves"],
        "calories_per_min": 3,
        "reps_default":     None,
        "sets_default":     2,
        "duration_seconds": 30,
        "ai_supported":     False,
        "instructions": [
            "Stand on one foot",
            "Place other foot on inner thigh or calf (not knee)",
            "Press foot and thigh together",
            "Bring hands to prayer position or raise overhead",
            "Fix gaze on a still point",
            "Hold for 5-10 breaths each side"
        ],
        "common_mistakes":  ["Placing foot on knee joint", "Gripping toes", "Tensing shoulders"],
        "reference_gif":    "",
    },
    {
        "name":             "Bridge Pose",
        "description":      "A backbend that strengthens the glutes, hamstrings, and lower back while opening the chest and hip flexors.",
        "primary_category": "Yoga",
        "categories":       ["Yoga", "Lower Body", "Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Glutes", "Hamstrings"],
        "muscles_secondary":["Lower Back", "Abs", "Hip Flexors"],
        "calories_per_min": 3,
        "reps_default":     10,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Lie on back with knees bent, feet flat",
            "Place feet hip-width apart near glutes",
            "Press feet into floor and lift hips",
            "Clasp hands under back",
            "Hold at top for 2-3 breaths",
            "Lower slowly"
        ],
        "common_mistakes":  ["Feet too far from body", "Knees splaying out", "Overarching lower back"],
        "reference_gif":    "",
    },
    {
        "name":             "Cat-Cow Stretch",
        "description":      "A flowing movement between two poses that warms up the spine, improves posture, and relieves back tension.",
        "primary_category": "Yoga",
        "categories":       ["Yoga", "Flexibility & Mobility", "Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Spinal Erectors", "Abs"],
        "muscles_secondary":["Neck", "Hip Flexors"],
        "calories_per_min": 2,
        "reps_default":     10,
        "sets_default":     2,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Start on hands and knees, wrists under shoulders",
            "Inhale: drop belly, lift chest and tailbone (Cow)",
            "Exhale: round spine toward ceiling, tuck chin (Cat)",
            "Move slowly with breath",
            "Repeat 10 times"
        ],
        "common_mistakes":  ["Moving too fast", "Holding breath", "Overextending neck"],
        "reference_gif":    "",
    },
    {
        "name":             "Seated Forward Bend",
        "description":      "A seated yoga pose that deeply stretches the hamstrings, spine, and lower back while calming the nervous system.",
        "primary_category": "Yoga",
        "categories":       ["Yoga", "Flexibility & Mobility"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Hamstrings", "Lower Back"],
        "muscles_secondary":["Calves", "Spine"],
        "calories_per_min": 2,
        "reps_default":     None,
        "sets_default":     3,
        "duration_seconds": 30,
        "ai_supported":     False,
        "instructions": [
            "Sit with legs extended straight",
            "Inhale and lengthen spine",
            "Exhale and hinge forward from hips",
            "Reach for feet, ankles, or shins",
            "Keep spine long, avoid rounding",
            "Hold for 30-60 seconds"
        ],
        "common_mistakes":  ["Rounding the back", "Forcing the stretch", "Bending knees"],
        "reference_gif":    "",
    },

    # ── 🏋️ STRENGTH TRAINING ─────────────────────────────────────────────────
    {
        "name":             "Push-ups",
        "description":      "A fundamental upper body exercise that builds chest, shoulder, and tricep strength using only bodyweight.",
        "primary_category": "Strength Training",
        "categories":       ["Strength Training", "Bodyweight Exercises", "Upper Body", "HIIT"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Chest", "Triceps"],
        "muscles_secondary":["Shoulders", "Abs", "Serratus Anterior"],
        "calories_per_min": 7,
        "reps_default":     15,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     True,
        "instructions": [
            "Start in plank position, hands shoulder-width apart",
            "Keep body in straight line from head to heels",
            "Lower chest to floor by bending elbows",
            "Keep elbows at 45 degrees from body",
            "Push back up to start",
            "Breathe in on the way down, out on the way up"
        ],
        "common_mistakes":  ["Sagging hips", "Flaring elbows", "Not going full range", "Head drooping"],
        "reference_gif":    "",
    },
    {
        "name":             "Pull-ups",
        "description":      "One of the best upper body exercises for building back width and bicep strength.",
        "primary_category": "Strength Training",
        "categories":       ["Strength Training", "Upper Body"],
        "difficulty":       "advanced",
        "equipment":        ["Pull-up bar"],
        "muscles_primary":  ["Lats", "Biceps"],
        "muscles_secondary":["Rear Deltoid", "Rhomboids", "Abs"],
        "calories_per_min": 8,
        "reps_default":     8,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Hang from bar with overhand grip, slightly wider than shoulders",
            "Start from dead hang with arms fully extended",
            "Pull yourself up until chin clears the bar",
            "Keep core tight throughout",
            "Lower slowly back to dead hang",
            "Avoid swinging or kipping"
        ],
        "common_mistakes":  ["Using momentum", "Partial range of motion", "Shrugging shoulders"],
        "reference_gif":    "",
    },
    {
        "name":             "Squats",
        "description":      "The king of lower body exercises. Builds strength in quads, hamstrings, and glutes while improving mobility.",
        "primary_category": "Strength Training",
        "categories":       ["Strength Training", "Bodyweight Exercises", "Lower Body", "HIIT"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps", "Glutes"],
        "muscles_secondary":["Hamstrings", "Calves", "Abs", "Lower Back"],
        "calories_per_min": 8,
        "reps_default":     15,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     True,
        "instructions": [
            "Stand with feet shoulder-width apart",
            "Point toes slightly outward",
            "Keep chest up and spine neutral",
            "Push hips back and bend knees",
            "Lower until thighs are parallel to floor",
            "Drive through heels to stand back up"
        ],
        "common_mistakes":  ["Knees caving inward", "Heels lifting", "Rounding back", "Not going deep enough"],
        "reference_gif":    "",
    },
    {
        "name":             "Lunges",
        "description":      "A unilateral lower body exercise that builds leg strength, improves balance, and corrects muscle imbalances.",
        "primary_category": "Strength Training",
        "categories":       ["Strength Training", "Bodyweight Exercises", "Lower Body"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps", "Glutes"],
        "muscles_secondary":["Hamstrings", "Calves", "Abs"],
        "calories_per_min": 7,
        "reps_default":     12,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     True,
        "instructions": [
            "Stand tall with feet hip-width apart",
            "Step forward with one leg",
            "Lower back knee toward floor",
            "Front knee should be at 90 degrees",
            "Keep front knee over ankle, not past toes",
            "Push back to start and alternate legs"
        ],
        "common_mistakes":  ["Front knee caving in", "Leaning torso forward", "Back knee slamming floor"],
        "reference_gif":    "",
    },
    {
        "name":             "Deadlifts",
        "description":      "A compound movement that builds total body strength, particularly in the posterior chain — hamstrings, glutes, and back.",
        "primary_category": "Strength Training",
        "categories":       ["Strength Training", "Lower Body"],
        "difficulty":       "intermediate",
        "equipment":        ["Dumbbells"],
        "muscles_primary":  ["Hamstrings", "Glutes", "Lower Back"],
        "muscles_secondary":["Quadriceps", "Lats", "Traps", "Abs"],
        "calories_per_min": 8,
        "reps_default":     10,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Stand with feet hip-width apart, dumbbells in front",
            "Hinge at hips and bend knees slightly",
            "Keep back flat, chest up",
            "Grip dumbbells with neutral grip",
            "Drive through heels to stand up",
            "Squeeze glutes at the top"
        ],
        "common_mistakes":  ["Rounding lower back", "Bar drifting from body", "Looking up too much"],
        "reference_gif":    "",
    },
    {
        "name":             "Shoulder Press",
        "description":      "An overhead pressing movement that builds strong, rounded shoulders and improves upper body pushing strength.",
        "primary_category": "Strength Training",
        "categories":       ["Strength Training", "Upper Body"],
        "difficulty":       "intermediate",
        "equipment":        ["Dumbbells"],
        "muscles_primary":  ["Shoulders", "Triceps"],
        "muscles_secondary":["Upper Chest", "Traps", "Abs"],
        "calories_per_min": 6,
        "reps_default":     12,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     True,
        "instructions": [
            "Sit or stand with dumbbells at shoulder height",
            "Palms facing forward",
            "Press dumbbells overhead until arms are extended",
            "Keep core tight, avoid arching back",
            "Lower slowly back to shoulder height",
            "Don't lock elbows at top"
        ],
        "common_mistakes":  ["Arching lower back", "Flaring elbows", "Uneven pressing"],
        "reference_gif":    "",
    },
    {
        "name":             "Bicep Curls",
        "description":      "An isolation exercise targeting the biceps. Essential for arm development and improving pulling strength.",
        "primary_category": "Strength Training",
        "categories":       ["Strength Training", "Upper Body"],
        "difficulty":       "beginner",
        "equipment":        ["Dumbbells"],
        "muscles_primary":  ["Biceps"],
        "muscles_secondary":["Forearms", "Brachialis"],
        "calories_per_min": 4,
        "reps_default":     12,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     True,
        "instructions": [
            "Stand with dumbbells at sides, palms forward",
            "Keep elbows close to body",
            "Curl dumbbells toward shoulders",
            "Squeeze biceps at top",
            "Lower slowly back to start",
            "Avoid swinging body"
        ],
        "common_mistakes":  ["Swinging body for momentum", "Elbows drifting forward", "Partial range of motion"],
        "reference_gif":    "",
    },
    {
        "name":             "Tricep Dips",
        "description":      "A bodyweight exercise that isolates the triceps using a chair or bench. Great for arm definition.",
        "primary_category": "Strength Training",
        "categories":       ["Strength Training", "Bodyweight Exercises", "Upper Body"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Triceps"],
        "muscles_secondary":["Chest", "Shoulders"],
        "calories_per_min": 6,
        "reps_default":     12,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Sit on edge of chair, hands gripping edge",
            "Slide off chair with legs extended",
            "Lower body by bending elbows to 90 degrees",
            "Keep back close to chair",
            "Push back up to start",
            "Keep shoulders down throughout"
        ],
        "common_mistakes":  ["Elbows flaring out", "Dropping too low", "Shoulders rising to ears"],
        "reference_gif":    "",
    },
    {
        "name":             "Bench Press",
        "description":      "The classic chest exercise for building upper body pushing strength and muscle mass.",
        "primary_category": "Strength Training",
        "categories":       ["Strength Training", "Upper Body"],
        "difficulty":       "intermediate",
        "equipment":        ["Dumbbells"],
        "muscles_primary":  ["Chest", "Triceps"],
        "muscles_secondary":["Anterior Deltoid", "Serratus Anterior"],
        "calories_per_min": 7,
        "reps_default":     10,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Lie on bench with dumbbells at chest level",
            "Feet flat on floor",
            "Press dumbbells up and slightly inward",
            "Keep slight arch in lower back",
            "Lower slowly until elbows at 90 degrees",
            "Drive back up explosively"
        ],
        "common_mistakes":  ["Bouncing off chest", "Flaring elbows", "Feet off floor"],
        "reference_gif":    "",
    },

    # ── ❤️ CARDIO ─────────────────────────────────────────────────────────────
    {
        "name":             "Jumping Jacks",
        "description":      "A classic full-body cardio exercise that raises heart rate quickly and improves coordination.",
        "primary_category": "Cardio",
        "categories":       ["Cardio", "HIIT", "Endurance & Stamina"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Calves", "Shoulders"],
        "muscles_secondary":["Glutes", "Hip Abductors"],
        "calories_per_min": 9,
        "reps_default":     30,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Stand with feet together, arms at sides",
            "Jump feet apart while raising arms overhead",
            "Immediately reverse the movement",
            "Land softly with bent knees",
            "Maintain steady rhythm",
            "Keep core engaged throughout"
        ],
        "common_mistakes":  ["Landing with straight knees", "Crossing feet", "Arms not reaching overhead"],
        "reference_gif":    "",
    },
    {
        "name":             "High Knees",
        "description":      "A high-intensity cardio exercise that improves running form, burns calories, and strengthens the core.",
        "primary_category": "Cardio",
        "categories":       ["Cardio", "HIIT"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Hip Flexors", "Quadriceps"],
        "muscles_secondary":["Calves", "Abs", "Glutes"],
        "calories_per_min": 10,
        "reps_default":     None,
        "sets_default":     3,
        "duration_seconds": 30,
        "ai_supported":     False,
        "instructions": [
            "Stand with feet hip-width apart",
            "Run in place lifting knees to hip height",
            "Pump arms in opposition to legs",
            "Land on balls of feet",
            "Keep core tight and chest up",
            "Maintain fast pace"
        ],
        "common_mistakes":  ["Not lifting knees high enough", "Leaning back", "Flat-footed landing"],
        "reference_gif":    "",
    },
    {
        "name":             "Burpees",
        "description":      "The ultimate full-body exercise that combines strength and cardio. Burns maximum calories in minimum time.",
        "primary_category": "Cardio",
        "categories":       ["Cardio", "HIIT", "Bodyweight Exercises"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Chest", "Quadriceps", "Shoulders"],
        "muscles_secondary":["Triceps", "Abs", "Calves", "Glutes"],
        "calories_per_min": 12,
        "reps_default":     10,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Stand with feet shoulder-width apart",
            "Drop into squat position, place hands on floor",
            "Jump feet back to plank position",
            "Perform one push-up",
            "Jump feet back to squat position",
            "Jump up with arms overhead"
        ],
        "common_mistakes":  ["Sagging hips in plank", "Skipping push-up", "Landing with straight knees"],
        "reference_gif":    "",
    },
    {
        "name":             "Mountain Climbers",
        "description":      "A dynamic exercise that combines core work with cardio, targeting multiple muscle groups simultaneously.",
        "primary_category": "Cardio",
        "categories":       ["Cardio", "HIIT", "Core & Abs", "Bodyweight Exercises"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Abs", "Hip Flexors"],
        "muscles_secondary":["Chest", "Shoulders", "Quadriceps"],
        "calories_per_min": 10,
        "reps_default":     None,
        "sets_default":     3,
        "duration_seconds": 30,
        "ai_supported":     False,
        "instructions": [
            "Start in high plank position",
            "Keep hips level with shoulders",
            "Drive one knee toward chest",
            "Quickly switch legs in running motion",
            "Keep core tight throughout",
            "Maintain fast, controlled pace"
        ],
        "common_mistakes":  ["Hips too high", "Bouncing hips", "Looking up"],
        "reference_gif":    "",
    },
    {
        "name":             "Jump Squats",
        "description":      "An explosive lower body exercise that builds power in the legs while elevating heart rate.",
        "primary_category": "Cardio",
        "categories":       ["Cardio", "HIIT", "Lower Body"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps", "Glutes"],
        "muscles_secondary":["Hamstrings", "Calves"],
        "calories_per_min": 10,
        "reps_default":     15,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Stand with feet shoulder-width apart",
            "Lower into squat position",
            "Explosively jump straight up",
            "Reach arms overhead",
            "Land softly with bent knees",
            "Immediately go into next squat"
        ],
        "common_mistakes":  ["Landing with straight knees", "Not squatting deep enough", "Leaning forward"],
        "reference_gif":    "",
    },
    {
        "name":             "Skipping Rope",
        "description":      "A high-calorie cardio exercise that improves coordination, agility, and cardiovascular fitness.",
        "primary_category": "Cardio",
        "categories":       ["Cardio", "Endurance & Stamina"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Calves", "Shoulders"],
        "muscles_secondary":["Abs", "Hip Flexors"],
        "calories_per_min": 12,
        "reps_default":     None,
        "sets_default":     3,
        "duration_seconds": 60,
        "ai_supported":     False,
        "instructions": [
            "Hold rope handles at hip height",
            "Jump on balls of feet",
            "Keep jumps small and controlled",
            "Rotate rope with wrists not arms",
            "Maintain upright posture",
            "Start slow, build speed gradually"
        ],
        "common_mistakes":  ["Jumping too high", "Using arms to swing rope", "Looking down"],
        "reference_gif":    "",
    },

    # ── 🤸 BODYWEIGHT EXERCISES ───────────────────────────────────────────────
    {
        "name":             "Plank",
        "description":      "The gold standard core exercise. Builds total core stability and endurance while engaging the entire body.",
        "primary_category": "Bodyweight Exercises",
        "categories":       ["Bodyweight Exercises", "Core & Abs", "Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Abs", "Spinal Erectors"],
        "muscles_secondary":["Shoulders", "Glutes", "Hip Flexors"],
        "calories_per_min": 5,
        "reps_default":     None,
        "sets_default":     3,
        "duration_seconds": 30,
        "ai_supported":     True,
        "instructions": [
            "Start in push-up position on forearms",
            "Elbows directly under shoulders",
            "Body forms straight line head to heels",
            "Engage core by pulling navel to spine",
            "Keep hips level — don't sag or pike",
            "Hold for target time while breathing normally"
        ],
        "common_mistakes":  ["Hips too high", "Hips sagging", "Holding breath", "Head drooping"],
        "reference_gif":    "",
    },
    {
        "name":             "Glute Bridge",
        "description":      "An effective exercise for activating and strengthening the glutes and hamstrings with no equipment needed.",
        "primary_category": "Bodyweight Exercises",
        "categories":       ["Bodyweight Exercises", "Lower Body", "Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Glutes", "Hamstrings"],
        "muscles_secondary":["Lower Back", "Abs"],
        "calories_per_min": 4,
        "reps_default":     15,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Lie on back with knees bent, feet flat",
            "Arms at sides, palms down",
            "Squeeze glutes and lift hips off floor",
            "Form straight line from knees to shoulders",
            "Hold for 2 seconds at top",
            "Lower slowly and repeat"
        ],
        "common_mistakes":  ["Pushing through lower back", "Feet too far away", "Not squeezing glutes"],
        "reference_gif":    "",
    },
    {
        "name":             "Wall Sit",
        "description":      "An isometric exercise that builds quad endurance and mental toughness with no equipment.",
        "primary_category": "Bodyweight Exercises",
        "categories":       ["Bodyweight Exercises", "Lower Body", "Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps"],
        "muscles_secondary":["Glutes", "Hamstrings", "Calves"],
        "calories_per_min": 4,
        "reps_default":     None,
        "sets_default":     3,
        "duration_seconds": 45,
        "ai_supported":     False,
        "instructions": [
            "Stand with back against wall",
            "Slide down until thighs are parallel to floor",
            "Feet shoulder-width apart, flat on floor",
            "Knees directly over ankles",
            "Keep back flat against wall",
            "Hold for target time"
        ],
        "common_mistakes":  ["Knees over toes", "Pushing off thighs with hands", "Back off wall"],
        "reference_gif":    "",
    },
    {
        "name":             "Superman Hold",
        "description":      "A back extension exercise that strengthens the posterior chain and improves posture.",
        "primary_category": "Bodyweight Exercises",
        "categories":       ["Bodyweight Exercises", "Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Spinal Erectors", "Glutes"],
        "muscles_secondary":["Hamstrings", "Rear Deltoid"],
        "calories_per_min": 3,
        "reps_default":     12,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Lie face down with arms extended overhead",
            "Simultaneously lift arms, chest, and legs off floor",
            "Squeeze glutes and back muscles",
            "Hold for 2-3 seconds",
            "Lower slowly",
            "Keep neck neutral throughout"
        ],
        "common_mistakes":  ["Jerking movement", "Holding breath", "Bending knees"],
        "reference_gif":    "",
    },
    {
        "name":             "Step-ups",
        "description":      "A functional lower body exercise using a step or box that builds unilateral leg strength and balance.",
        "primary_category": "Bodyweight Exercises",
        "categories":       ["Bodyweight Exercises", "Lower Body", "Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps", "Glutes"],
        "muscles_secondary":["Hamstrings", "Calves"],
        "calories_per_min": 6,
        "reps_default":     12,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Stand in front of a step or bench",
            "Place one foot fully on the step",
            "Drive through heel to step up",
            "Bring other foot up to meet it",
            "Step back down with control",
            "Alternate leading leg"
        ],
        "common_mistakes":  ["Pushing off back foot", "Leaning forward", "Step too high"],
        "reference_gif":    "",
    },

    # ── 🧠 CORE / ABS ─────────────────────────────────────────────────────────
    {
        "name":             "Crunches",
        "description":      "A classic abdominal exercise targeting the upper abs. Simple yet effective for core development.",
        "primary_category": "Core & Abs",
        "categories":       ["Core & Abs"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Abs"],
        "muscles_secondary":["Hip Flexors"],
        "calories_per_min": 5,
        "reps_default":     20,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Lie on back with knees bent",
            "Place hands behind head lightly",
            "Engage core and lift shoulder blades off floor",
            "Focus on contracting abs, not pulling neck",
            "Lower slowly back down",
            "Don't let head touch floor between reps"
        ],
        "common_mistakes":  ["Pulling neck with hands", "Full sit-up motion", "Holding breath"],
        "reference_gif":    "",
    },
    {
        "name":             "Leg Raises",
        "description":      "An effective lower ab exercise that targets the hip flexors and builds core strength.",
        "primary_category": "Core & Abs",
        "categories":       ["Core & Abs"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Lower Abs", "Hip Flexors"],
        "muscles_secondary":["Quadriceps"],
        "calories_per_min": 5,
        "reps_default":     15,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Lie flat on back, arms at sides",
            "Keep legs straight",
            "Raise legs to 90 degrees",
            "Lower slowly without touching floor",
            "Keep lower back pressed to floor",
            "Breathe out on the way up"
        ],
        "common_mistakes":  ["Lower back arching", "Bending knees", "Swinging legs down"],
        "reference_gif":    "",
    },
    {
        "name":             "Russian Twists",
        "description":      "A rotational core exercise that targets the obliques and improves rotational strength.",
        "primary_category": "Core & Abs",
        "categories":       ["Core & Abs"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Obliques", "Abs"],
        "muscles_secondary":["Hip Flexors", "Lower Back"],
        "calories_per_min": 6,
        "reps_default":     20,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Sit with knees bent, feet off floor",
            "Lean back slightly to engage core",
            "Clasp hands together or hold weight",
            "Rotate torso to the right",
            "Return to center and rotate left",
            "Keep chest up throughout"
        ],
        "common_mistakes":  ["Moving arms instead of torso", "Feet on floor (too easy)", "Rounding back"],
        "reference_gif":    "",
    },
    {
        "name":             "Bicycle Crunch",
        "description":      "One of the most effective ab exercises that targets both the upper abs and obliques simultaneously.",
        "primary_category": "Core & Abs",
        "categories":       ["Core & Abs"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Abs", "Obliques"],
        "muscles_secondary":["Hip Flexors"],
        "calories_per_min": 6,
        "reps_default":     20,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Lie on back, hands behind head",
            "Lift shoulders off floor",
            "Bring right knee to chest while rotating left elbow toward it",
            "Simultaneously extend left leg",
            "Switch sides in cycling motion",
            "Keep lower back pressed to floor"
        ],
        "common_mistakes":  ["Pulling neck", "Rushing through reps", "Hips rotating off floor"],
        "reference_gif":    "",
    },
    {
        "name":             "Side Plank",
        "description":      "A lateral core stability exercise that targets the obliques and improves lateral spine stability.",
        "primary_category": "Core & Abs",
        "categories":       ["Core & Abs"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Obliques", "Abs"],
        "muscles_secondary":["Shoulders", "Glutes", "Hip Abductors"],
        "calories_per_min": 5,
        "reps_default":     None,
        "sets_default":     3,
        "duration_seconds": 30,
        "ai_supported":     False,
        "instructions": [
            "Lie on side with elbow under shoulder",
            "Stack feet on top of each other",
            "Lift hips off floor",
            "Body forms straight diagonal line",
            "Hold without letting hips drop",
            "Hold each side for target time"
        ],
        "common_mistakes":  ["Hips sagging", "Shoulder rolling forward", "Holding breath"],
        "reference_gif":    "",
    },
    {
        "name":             "Flutter Kicks",
        "description":      "A continuous lower ab exercise that builds endurance in the core and hip flexors.",
        "primary_category": "Core & Abs",
        "categories":       ["Core & Abs"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Lower Abs", "Hip Flexors"],
        "muscles_secondary":["Quadriceps"],
        "calories_per_min": 5,
        "reps_default":     None,
        "sets_default":     3,
        "duration_seconds": 30,
        "ai_supported":     False,
        "instructions": [
            "Lie flat on back, arms at sides",
            "Raise both legs 6 inches off floor",
            "Alternate kicking legs up and down",
            "Keep lower back pressed to floor",
            "Keep legs straight throughout",
            "Maintain steady breathing"
        ],
        "common_mistakes":  ["Lower back arching off floor", "Bending knees", "Raising legs too high"],
        "reference_gif":    "",
    },

    # ── 🧘‍♂️ FLEXIBILITY & MOBILITY ───────────────────────────────────────────
    {
        "name":             "Hamstring Stretch",
        "description":      "A fundamental stretch for the back of the legs. Essential after leg workouts and for injury prevention.",
        "primary_category": "Flexibility & Mobility",
        "categories":       ["Flexibility & Mobility", "Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Hamstrings"],
        "muscles_secondary":["Lower Back", "Calves"],
        "calories_per_min": 1,
        "reps_default":     None,
        "sets_default":     2,
        "duration_seconds": 30,
        "ai_supported":     False,
        "instructions": [
            "Sit on floor with one leg extended",
            "Bend other leg with foot against inner thigh",
            "Reach toward extended foot",
            "Keep back straight, hinge from hips",
            "Hold the stretch, breathe deeply",
            "Repeat on other side"
        ],
        "common_mistakes":  ["Rounding back", "Forcing the stretch", "Bouncing"],
        "reference_gif":    "",
    },
    {
        "name":             "Hip Flexor Stretch",
        "description":      "A critical stretch for people who sit for long periods. Opens tight hip flexors and reduces lower back pain.",
        "primary_category": "Flexibility & Mobility",
        "categories":       ["Flexibility & Mobility", "Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Hip Flexors"],
        "muscles_secondary":["Quadriceps", "Lower Back"],
        "calories_per_min": 1,
        "reps_default":     None,
        "sets_default":     2,
        "duration_seconds": 30,
        "ai_supported":     False,
        "instructions": [
            "Kneel on one knee, other foot forward",
            "Front knee over front ankle",
            "Push hips slightly forward",
            "Keep torso upright",
            "Feel stretch in front of back hip",
            "Hold and repeat on other side"
        ],
        "common_mistakes":  ["Front knee past toes", "Leaning forward", "Arching lower back"],
        "reference_gif":    "",
    },
    {
        "name":             "Shoulder Stretch",
        "description":      "A simple stretch to relieve shoulder tension, improve posture, and increase upper body mobility.",
        "primary_category": "Flexibility & Mobility",
        "categories":       ["Flexibility & Mobility", "Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Posterior Deltoid", "Rotator Cuff"],
        "muscles_secondary":["Triceps", "Upper Back"],
        "calories_per_min": 1,
        "reps_default":     None,
        "sets_default":     2,
        "duration_seconds": 30,
        "ai_supported":     False,
        "instructions": [
            "Bring one arm across chest",
            "Use other hand to gently pull arm in",
            "Feel stretch in back of shoulder",
            "Keep shoulder down, not raised",
            "Hold for 30 seconds",
            "Repeat on other side"
        ],
        "common_mistakes":  ["Pulling too hard", "Shoulder shrugging", "Rotating torso"],
        "reference_gif":    "",
    },
    {
        "name":             "World's Greatest Stretch",
        "description":      "A multi-joint dynamic stretch that opens the hips, thoracic spine, and hamstrings in one movement.",
        "primary_category": "Flexibility & Mobility",
        "categories":       ["Flexibility & Mobility"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Hip Flexors", "Thoracic Spine"],
        "muscles_secondary":["Hamstrings", "Glutes", "Shoulders"],
        "calories_per_min": 3,
        "reps_default":     5,
        "sets_default":     2,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Start in lunge position with right foot forward",
            "Place left hand on floor beside right foot",
            "Rotate right arm up toward ceiling",
            "Hold, then bring arm back down",
            "Push back into hamstring stretch",
            "Repeat on other side"
        ],
        "common_mistakes":  ["Rushing through movement", "Not rotating fully", "Back knee touching floor"],
        "reference_gif":    "",
    },
    {
        "name":             "Arm Circles",
        "description":      "A warm-up exercise that increases blood flow to the shoulders and improves joint mobility.",
        "primary_category": "Flexibility & Mobility",
        "categories":       ["Flexibility & Mobility", "Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Shoulders", "Rotator Cuff"],
        "muscles_secondary":["Upper Back", "Chest"],
        "calories_per_min": 2,
        "reps_default":     None,
        "sets_default":     2,
        "duration_seconds": 30,
        "ai_supported":     False,
        "instructions": [
            "Stand with arms extended to sides",
            "Make small circles forward for 15 seconds",
            "Gradually increase circle size",
            "Reverse direction for 15 seconds",
            "Keep shoulders relaxed",
            "Stand tall throughout"
        ],
        "common_mistakes":  ["Hunching shoulders", "Moving torso", "Circles too fast"],
        "reference_gif":    "",
    },

    # ── ⚡ HIIT ───────────────────────────────────────────────────────────────
    {
        "name":             "Plank Jacks",
        "description":      "A plank variation that adds a cardio element by jumping feet in and out, challenging core stability.",
        "primary_category": "HIIT",
        "categories":       ["HIIT", "Core & Abs"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Abs", "Shoulders"],
        "muscles_secondary":["Hip Abductors", "Glutes"],
        "calories_per_min": 9,
        "reps_default":     None,
        "sets_default":     3,
        "duration_seconds": 30,
        "ai_supported":     False,
        "instructions": [
            "Start in high plank position",
            "Jump both feet out wide simultaneously",
            "Jump feet back together",
            "Keep hips level throughout",
            "Maintain strong plank position",
            "Move at quick pace"
        ],
        "common_mistakes":  ["Hips bouncing", "Arms bending", "Looking up"],
        "reference_gif":    "",
    },
    {
        "name":             "Skater Jumps",
        "description":      "A lateral plyometric exercise that builds power, agility, and coordination while burning calories.",
        "primary_category": "HIIT",
        "categories":       ["HIIT", "Lower Body"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Glutes", "Quadriceps"],
        "muscles_secondary":["Calves", "Hip Abductors"],
        "calories_per_min": 10,
        "reps_default":     20,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Stand on left foot with slight knee bend",
            "Jump laterally to the right",
            "Land on right foot, swinging left leg behind",
            "Immediately jump back to the left",
            "Swing arms for momentum",
            "Stay low throughout"
        ],
        "common_mistakes":  ["Landing with straight knee", "Not jumping far enough", "Standing too tall"],
        "reference_gif":    "",
    },
    {
        "name":             "Tuck Jumps",
        "description":      "An explosive plyometric exercise that develops power and burns maximum calories.",
        "primary_category": "HIIT",
        "categories":       ["HIIT"],
        "difficulty":       "advanced",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps", "Calves"],
        "muscles_secondary":["Glutes", "Abs", "Hip Flexors"],
        "calories_per_min": 12,
        "reps_default":     10,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Stand with feet shoulder-width apart",
            "Bend knees slightly",
            "Jump as high as possible",
            "Bring knees to chest at top of jump",
            "Land softly with bent knees",
            "Immediately jump again"
        ],
        "common_mistakes":  ["Not bringing knees high enough", "Landing with straight knees", "Leaning too far forward"],
        "reference_gif":    "",
    },
    {
        "name":             "Jump Lunges",
        "description":      "A plyometric lunge variation that develops explosive leg power while burning high calories.",
        "primary_category": "HIIT",
        "categories":       ["HIIT", "Lower Body"],
        "difficulty":       "advanced",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps", "Glutes"],
        "muscles_secondary":["Hamstrings", "Calves"],
        "calories_per_min": 11,
        "reps_default":     12,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Start in lunge position",
            "Lower back knee toward floor",
            "Explosively jump up",
            "Switch legs in midair",
            "Land in lunge with opposite leg forward",
            "Immediately lower into next lunge"
        ],
        "common_mistakes":  ["Landing with straight knees", "Front knee caving in", "Upper body lurching"],
        "reference_gif":    "",
    },

    # ── 🏃 ENDURANCE / STAMINA ────────────────────────────────────────────────
    {
        "name":             "Jogging in Place",
        "description":      "A simple endurance exercise done anywhere to build cardiovascular fitness and stamina.",
        "primary_category": "Endurance & Stamina",
        "categories":       ["Endurance & Stamina", "Cardio"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps", "Calves"],
        "muscles_secondary":["Glutes", "Hamstrings"],
        "calories_per_min": 7,
        "reps_default":     None,
        "sets_default":     3,
        "duration_seconds": 60,
        "ai_supported":     False,
        "instructions": [
            "Stand with feet hip-width apart",
            "Lift knees to comfortable height",
            "Land on balls of feet",
            "Pump arms naturally",
            "Maintain steady comfortable pace",
            "Keep breathing rhythmic"
        ],
        "common_mistakes":  ["Flat-footed landing", "Arms crossing body", "Hunching forward"],
        "reference_gif":    "",
    },
    {
        "name":             "Brisk Walking",
        "description":      "An accessible endurance exercise for all fitness levels. Excellent for active recovery and building base fitness.",
        "primary_category": "Endurance & Stamina",
        "categories":       ["Endurance & Stamina", "Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps", "Glutes"],
        "muscles_secondary":["Calves", "Hamstrings"],
        "calories_per_min": 5,
        "reps_default":     None,
        "sets_default":     1,
        "duration_seconds": 1800,
        "ai_supported":     False,
        "instructions": [
            "Walk at purposeful pace (can hold conversation but slightly breathless)",
            "Swing arms naturally",
            "Land heel first, roll to toe",
            "Keep posture upright",
            "Target 100 steps per minute",
            "Aim for 30 minutes continuously"
        ],
        "common_mistakes":  ["Walking too slowly", "Looking down at phone", "Short shuffling steps"],
        "reference_gif":    "",
    },

    # ── 🏋️‍♂️ UPPER BODY ──────────────────────────────────────────────────────
    {
        "name":             "Lateral Raises",
        "description":      "An isolation exercise for the medial deltoid that builds the width and roundness of the shoulders.",
        "primary_category": "Upper Body",
        "categories":       ["Upper Body", "Strength Training"],
        "difficulty":       "beginner",
        "equipment":        ["Dumbbells"],
        "muscles_primary":  ["Medial Deltoid"],
        "muscles_secondary":["Anterior Deltoid", "Traps"],
        "calories_per_min": 4,
        "reps_default":     15,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Stand with dumbbells at sides",
            "Slight bend in elbows",
            "Raise arms to sides until shoulder height",
            "Lead with elbows not wrists",
            "Pause at top, lower slowly",
            "Keep slight forward lean"
        ],
        "common_mistakes":  ["Shrugging shoulders", "Using momentum", "Raising above shoulder height"],
        "reference_gif":    "",
    },
    {
        "name":             "Tricep Extensions",
        "description":      "An overhead isolation movement that stretches and strengthens the triceps through full range of motion.",
        "primary_category": "Upper Body",
        "categories":       ["Upper Body", "Strength Training"],
        "difficulty":       "beginner",
        "equipment":        ["Dumbbells"],
        "muscles_primary":  ["Triceps"],
        "muscles_secondary":["Shoulders"],
        "calories_per_min": 4,
        "reps_default":     12,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Hold dumbbell overhead with both hands",
            "Elbows pointing forward near ears",
            "Lower dumbbell behind head",
            "Keep upper arms stationary",
            "Extend arms back to start",
            "Control the descent"
        ],
        "common_mistakes":  ["Elbows flaring wide", "Moving upper arms", "Too heavy a weight"],
        "reference_gif":    "",
    },
    {
        "name":             "Pike Push-ups",
        "description":      "A push-up variation that shifts emphasis to the shoulders, serving as a stepping stone to handstand push-ups.",
        "primary_category": "Upper Body",
        "categories":       ["Upper Body", "Bodyweight Exercises"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Shoulders", "Triceps"],
        "muscles_secondary":["Upper Chest", "Abs"],
        "calories_per_min": 7,
        "reps_default":     10,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Start in downward dog position",
            "Hips high, body forming inverted V",
            "Bend elbows to lower head toward floor",
            "Keep elbows tracking back not out",
            "Push back up to start",
            "Focus on shoulder engagement"
        ],
        "common_mistakes":  ["Hips dropping during movement", "Elbows flaring", "Head not reaching floor"],
        "reference_gif":    "",
    },

    # ── 🦵 LOWER BODY ─────────────────────────────────────────────────────────
    {
        "name":             "Calf Raises",
        "description":      "A targeted lower leg exercise that builds calf muscle size and strength.",
        "primary_category": "Lower Body",
        "categories":       ["Lower Body"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Calves"],
        "muscles_secondary":["Soleus", "Achilles Tendon"],
        "calories_per_min": 4,
        "reps_default":     20,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Stand with feet hip-width apart",
            "Rise onto balls of feet as high as possible",
            "Hold briefly at top",
            "Lower slowly back to floor",
            "Full range of motion is key",
            "Hold wall for balance if needed"
        ],
        "common_mistakes":  ["Rushing the movement", "Partial range of motion", "Leaning forward"],
        "reference_gif":    "",
    },
    {
        "name":             "Bulgarian Split Squat",
        "description":      "An advanced unilateral leg exercise that builds quad and glute strength while improving balance.",
        "primary_category": "Lower Body",
        "categories":       ["Lower Body", "Strength Training"],
        "difficulty":       "advanced",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps", "Glutes"],
        "muscles_secondary":["Hamstrings", "Calves", "Abs"],
        "calories_per_min": 8,
        "reps_default":     10,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Stand 2 feet in front of a bench",
            "Place rear foot on bench behind you",
            "Lower front leg until thigh is parallel",
            "Keep front knee over ankle",
            "Drive through front heel to stand",
            "Complete all reps before switching"
        ],
        "common_mistakes":  ["Front foot too close to bench", "Knee caving in", "Leaning too far forward"],
        "reference_gif":    "",
    },
    {
        "name":             "Hip Thrust",
        "description":      "The most effective glute exercise. Isolates and maximally activates the glutes better than squats.",
        "primary_category": "Lower Body",
        "categories":       ["Lower Body"],
        "difficulty":       "intermediate",
        "equipment":        ["None"],
        "muscles_primary":  ["Glutes"],
        "muscles_secondary":["Hamstrings", "Abs", "Hip Flexors"],
        "calories_per_min": 5,
        "reps_default":     15,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Sit with upper back against bench",
            "Feet flat on floor, hip-width apart",
            "Drive through heels to thrust hips up",
            "Squeeze glutes hard at top",
            "Form straight line from knees to shoulders",
            "Lower slowly and repeat"
        ],
        "common_mistakes":  ["Chin tucked to chest", "Not squeezing glutes at top", "Feet too far away"],
        "reference_gif":    "",
    },

    # ── 🧩 REHABILITATION / LOW IMPACT ────────────────────────────────────────
    {
        "name":             "Wall Push-ups",
        "description":      "A beginner-friendly push-up variation using a wall for support. Perfect for those building upper body strength from scratch.",
        "primary_category": "Rehabilitation",
        "categories":       ["Rehabilitation", "Upper Body"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Chest", "Triceps"],
        "muscles_secondary":["Shoulders", "Abs"],
        "calories_per_min": 3,
        "reps_default":     15,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Stand arm's length from wall",
            "Place hands on wall at shoulder height",
            "Lean forward and lower chest to wall",
            "Keep body in straight line",
            "Push back to start",
            "Step further from wall to increase difficulty"
        ],
        "common_mistakes":  ["Hips sagging", "Elbows flaring", "Moving too fast"],
        "reference_gif":    "",
    },
    {
        "name":             "Seated Leg Raises",
        "description":      "A low-impact exercise for strengthening the quads and hip flexors, suitable for rehabilitation and beginners.",
        "primary_category": "Rehabilitation",
        "categories":       ["Rehabilitation", "Lower Body"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps", "Hip Flexors"],
        "muscles_secondary":["Abs"],
        "calories_per_min": 2,
        "reps_default":     15,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Sit upright in a chair",
            "Hold chair sides for stability",
            "Straighten one leg and raise to hip height",
            "Hold for 2 seconds",
            "Lower slowly",
            "Alternate legs"
        ],
        "common_mistakes":  ["Leaning back", "Raising leg too high", "Rushing movement"],
        "reference_gif":    "",
    },
    {
        "name":             "Heel Raises",
        "description":      "A gentle ankle strengthening exercise ideal for rehabilitation after ankle injuries or surgery.",
        "primary_category": "Rehabilitation",
        "categories":       ["Rehabilitation"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Calves", "Achilles Tendon"],
        "muscles_secondary":["Soleus"],
        "calories_per_min": 2,
        "reps_default":     20,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Stand near wall for support",
            "Rise slowly onto toes",
            "Hold for 2 seconds",
            "Lower slowly back down",
            "Focus on controlled movement",
            "Can be done on one leg for progression"
        ],
        "common_mistakes":  ["Moving too fast", "Not holding at top", "Leaning on support too much"],
        "reference_gif":    "",
    },
    {
        "name":             "Resistance Band Pull",
        "description":      "A low-impact upper back exercise using a resistance band. Excellent for posture correction and shoulder health.",
        "primary_category": "Rehabilitation",
        "categories":       ["Rehabilitation", "Upper Body"],
        "difficulty":       "beginner",
        "equipment":        ["Resistance bands"],
        "muscles_primary":  ["Rear Deltoid", "Rhomboids"],
        "muscles_secondary":["Traps", "Biceps"],
        "calories_per_min": 3,
        "reps_default":     15,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Hold band at both ends, arms extended",
            "Pull band apart horizontally",
            "Squeeze shoulder blades together",
            "Hold for 2 seconds",
            "Release slowly",
            "Keep shoulders down throughout"
        ],
        "common_mistakes":  ["Shrugging shoulders", "Bending elbows", "Moving too fast"],
        "reference_gif":    "",
    },
    {
        "name":             "Chair Squats",
        "description":      "A beginner-friendly squat variation using a chair for guidance and safety. Perfect for building confidence and strength.",
        "primary_category": "Rehabilitation",
        "categories":       ["Rehabilitation", "Lower Body"],
        "difficulty":       "beginner",
        "equipment":        ["None"],
        "muscles_primary":  ["Quadriceps", "Glutes"],
        "muscles_secondary":["Hamstrings", "Calves"],
        "calories_per_min": 4,
        "reps_default":     12,
        "sets_default":     3,
        "duration_seconds": None,
        "ai_supported":     False,
        "instructions": [
            "Stand in front of chair, feet shoulder-width",
            "Push hips back and lower toward chair",
            "Lightly touch chair but don't sit",
            "Drive through heels to stand",
            "Arms forward for balance",
            "Keep chest up throughout"
        ],
        "common_mistakes":  ["Fully sitting down", "Knees caving in", "Looking down"],
        "reference_gif":    "",
    },
]


# ─── Main seeder ──────────────────────────────────────────────────────────────
def main():
    print("=" * 60)
    print("AI Home Gym — Curated Exercise Seeder")
    print("=" * 60)

    # Connect
    print("\n[1/3] Connecting to MongoDB...")
    try:
        client = pymongo.MongoClient(MONGO_URI, serverSelectionTimeoutMS=5000)
        client.admin.command("ping")
        db = client.ai_home_gym
        print("  ✅ Connected")
    except Exception as e:
        print(f"  ❌ MongoDB connection failed: {e}")
        sys.exit(1)

    # Validate data
    print("\n[2/3] Validating exercise data...")
    for ex in EXERCISES:
        assert "name"             in ex, f"Missing name"
        assert "primary_category" in ex, f"Missing primary_category in {ex['name']}"
        assert "difficulty"       in ex, f"Missing difficulty in {ex['name']}"
        assert "ai_supported"     in ex, f"Missing ai_supported in {ex['name']}"
    print(f"  ✅ {len(EXERCISES)} exercises validated")

    # Insert
    print("\n[3/3] Clearing old data and inserting curated exercises...")
    db.exercises.drop()

    # Create indexes
    db.exercises.create_index("name",             unique=True)
    db.exercises.create_index("primary_category")
    db.exercises.create_index("categories")
    db.exercises.create_index("difficulty")
    db.exercises.create_index("ai_supported")
    db.exercises.create_index([
        ("name", "text"),
        ("description", "text"),
        ("muscles_primary", "text"),
    ])

    # Add metadata to each exercise
    now = datetime.utcnow()
    for ex in EXERCISES:
        ex["rating"]       = 0.0
        ex["rating_count"] = 0
        ex["times_used"]   = 0
        ex["is_active"]    = True
        ex["source"]       = "curated"
        ex["created_at"]   = now
        ex["updated_at"]   = now

    result = db.exercises.insert_many(EXERCISES)
    print(f"  ✅ Inserted {len(result.inserted_ids)} exercises")

    # Summary
    print("\n" + "=" * 60)
    print("SEEDING COMPLETE")
    print("=" * 60)
    pipeline = [
        {"$unwind": "$categories"},
        {"$group": {"_id": "$categories", "count": {"$sum": 1}}},
        {"$sort": {"count": -1}},
    ]
    for doc in db.exercises.aggregate(pipeline):
        ai_count = db.exercises.count_documents({
            "categories": doc["_id"],
            "ai_supported": True,
        })
        ai_str = f"  ({ai_count} AI-supported)" if ai_count > 0 else ""
        print(f"  {doc['_id']:30s}: {doc['count']:3d} exercises{ai_str}")

    total    = db.exercises.count_documents({})
    ai_total = db.exercises.count_documents({"ai_supported": True})
    print(f"\n  Total unique exercises : {total}")
    print(f"  AI form detection ready: {ai_total}")
    print("=" * 60)
    client.close()


if __name__ == "__main__":
    main()